### ISSUE TITLE
Add support for tracking which guns notifications has been sent for

### ISSUE THREAD

**Issue by 95ep** [95ep/GunScraper#8]
- [ ] Store IDs of guns when sending notifications in persistent file
- [ ] Cross reference guns found with ID of already sent
- [ ] Removal of old IDs when no longer relevant to avoid growing file. When no longer present on corresponding site?
